In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
from sklearn.datasets import load_digits
X_digits, y_digits = load_digits(return_X_y=True)

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_digits, y_digits)

In [4]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [5]:
from sklearn.cluster import KMeans

k = 50
kmeans = KMeans(n_clusters=k)
X_digits_dist = kmeans.fit_transform(X_train)
representative_digit_idx = np.argmin(X_digits_dist, axis=0)
X_representative_digits = X_train[representative_digit_idx]

In [6]:
kmeans.labels_

array([33, 47, 33, ..., 47, 44, 37], dtype=int32)

In [7]:
np.arange(len(X_train))

array([   0,    1,    2, ..., 1344, 1345, 1346])

In [11]:
X_digits_dist.shape

(1347, 50)

In [12]:
X_cluster_dist = X_digits_dist[np.arange(len(X_train)), kmeans.labels_]

In [13]:
X_cluster_dist

array([19.6944944 , 17.25286519, 22.26417801, ..., 21.93838956,
       20.52962187, 20.16345245])

In [14]:
len(X_cluster_dist)

1347

In [15]:
a = np.array([1,2,3,4])

In [16]:
a

array([1, 2, 3, 4])

In [18]:
a[2][1]

IndexError: invalid index to scalar variable.

In [24]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=1000, noise=0.05)
dbscan = DBSCAN(eps=0.2, min_samples=5)
dbscan.fit(X)

DBSCAN(eps=0.2)

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

In [26]:
y_dist, y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)

In [27]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])

In [28]:
knn.predict(X_new)

array([1, 0, 1, 0])

In [29]:
knn.predict_proba(X_new)

array([[0.08, 0.92],
       [1.  , 0.  ],
       [0.18, 0.82],
       [1.  , 0.  ]])

In [30]:
y_dist, y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)

In [31]:
y_dist

array([[0.39478585],
       [0.00832419],
       [0.04723057],
       [0.4600445 ]])

In [33]:
y_pred_idx

array([[924],
       [668],
       [600],
       [951]])

In [35]:
dbscan.labels_.shape

(1000,)

In [36]:
dbscan.core_sample_indices_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [37]:
y_pred = dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]

In [38]:
y_pred

array([[1],
       [0],
       [1],
       [0]])

In [39]:
y_pred[y_dist > 0.2] = -1

In [40]:
y_pred.ravel()

array([-1,  0,  1, -1])

In [49]:
len(dbscan.labels_)

1000

In [54]:
dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx][0]

array([1])

In [51]:
y_pred_idx

array([[924],
       [668],
       [600],
       [951]])

In [55]:
b = np.array([1,2,3,4,5,6,7,8,9,10])

In [56]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
a = range(5)
a

range(0, 5)

In [66]:
b[a][range(2)][1]

2